#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=2

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chown -R $app:www-data $install_dir
chmod o-rwx $install_dir

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=3

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" < "$install_dir/results/telemetry_mysql.sql"

#=================================================
# CONFIGURE LIBRESPEED
#=================================================
ynh_script_progression --message="Configuring $app..." --weight=3

ynh_add_config --template="../conf/telemetry_settings.php" --destination="$install_dir/results/telemetry_settings.php"
ynh_add_config --template="../conf/example-singleServer-full.html" --destination="$install_dir/singleServer-full.html"

chmod 400 "$install_dir/results/telemetry_settings.php"
chmod 400 "$install_dir/singleServer-full.html"
chown $app:$app "$install_dir/results/telemetry_settings.php"
chown $app:$app "$install_dir/singleServer-full.html"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
