#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=256M

ynh_app_setting_set --key=password --value="$password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data $install_dir
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod o-rwx $install_dir
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

ynh_mysql_db_shell < "$install_dir/results/telemetry_mysql.sql"

#=================================================
# CONFIGURE LIBRESPEED
#=================================================
ynh_script_progression "Configuring $app..."

ynh_config_add --template="telemetry_settings.php" --destination="$install_dir/results/telemetry_settings.php"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 650 "$install_dir/results/telemetry_settings.php"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:www-data "$install_dir/results/telemetry_settings.php"

ynh_config_add --template="example-singleServer-full.html" --destination="$install_dir/index.html"
chmod 650 "$install_dir/index.html"
chown $app:www-data "$install_dir/index.html"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
