#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="results/telemetry_settings.php index.html"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# CONFIGURE LIBRESPEED
#=================================================
ynh_script_progression "Reconfiguring $app..."

ynh_config_add --template="telemetry_settings.php" --destination="$install_dir/results/telemetry_settings.php"
chmod 650 "$install_dir/results/telemetry_settings.php"
chown $app:www-data "$install_dir/results/telemetry_settings.php"

ynh_config_add --template="example-singleServer-full.html" --destination="$install_dir/index.html"
chmod 650 "$install_dir/index.html"
chown $app:www-data "$install_dir/index.html"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
