#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="results/telemetry_settings.php index.html"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# CONFIGURE LIBRESPEED
#=================================================

if ynh_app_upstream_version_changed
then
    ynh_script_progression "Reconfiguring LibreSpeed..."

    ynh_config_add --template="telemetry_settings.php" --destination="$install_dir/results/telemetry_settings.php"
    chmod 650 "$install_dir/results/telemetry_settings.php"
    chown $app:www-data "$install_dir/results/telemetry_settings.php"

    ynh_config_add --template="example-singleServer-full.html" --destination="$install_dir/index.html"
    chmod 650 "$install_dir/index.html"
    chown $app:www-data "$install_dir/index.html"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
